### ISSUE TITLE
DNS-only route with no RCM hacks?

### ISSUE THREAD

**Issue by petersvp** [kinnay/SMB35#13]
Is it possible that this open source server is made workable by only DNS modding? E.g. a DNS server that serves your server IP instead of the actual Arika/Nintendo one? I believe it will be possible and you should focus on this. I prefer to not mod my switch and it will be much more accessible for everyone if possible.

**Comment by just-another-random-person** [comment]
Before you can connect online on the Switch, it connects to Nintendo's dauth (device authorization) and aauth (application authorization) https servers. This provides a response signed by Nintendo that you are allowed to go online (banned units aren't given such a response).

Explained better by SciresM (author of Atmosphere):

https://www.reddit.com/r/SwitchHacks/comments/8rxg26/psa_strong_antipiracy_measures_implemented_by/

So it's impossible to do anything "custom-server" like unless you actually patch the system and the game.

**Comment by kinnay** [comment]
@just-another-random-person is right. This is impossible. All servers use TLS, including the game server. If one could replace a server by DNS modding, TLS would not be secure.
