### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by mosh5382** [kinnay/SMB35#14]
Please renew the Let's Encrypt certificate for https://smb35.ymar.dev:20002 as it expired on July 18th.

**Comment by kinnay** [comment]
Thank you. The certificate is now valid until October 5th.

It would be better if the certificate was renewed automatically. That should be easy, because certbot renews the certificates automatically anyway. I'll keep this issue open to remind me to work on it.

**Comment by InternalLoss** [comment]
> Thank you. The certificate is now valid until October 5th.
> 
> It would be better if the certificate was renewed automatically. That should be easy, because certbot renews the certificates automatically anyway. I'll keep this issue open to remind me to work on it.

Set a post-command hook in certbot config, to restart the server after the certificate itself gets updated.
