### ISSUE TITLE
Participants Limit

### ISSUE THREAD

**Issue by PhynixP** [kinnay/SMB35#2]
Hello kinnay,
i have a question to participants, is it possible to limit the max participants from ( 35 ) to ( 5 )for example ?
It is a good feature for nearly server test

**Comment by kinnay** [comment]
Not easily. The maximum number of participants is specified by the game.

You might be able to update the maximum number of participants on the server side here: https://github.com/kinnay/SMB35/blob/master/source/main.py#L330

Set `param.session.max_participants` to 5 at the start of this function.

It might cause problems if the game expects the maximum number of participants to be 35 though.

**Comment by PhynixP** [comment]
I didn't quite understand that now.
where exactly must the 5 be placed.

if param.session.max_participants <param.num_participants:

**Comment by kinnay** [comment]
I would probably try something like this:

```python
async def auto_matchmake_with_param_postpone(self, client, param):
    param.session.max_participants = 5
    
    if param.session.max_participants < param.num_participants:
        raise common.RMCError("Core::InvalidArgument")
```

If a session has 5 participants, this will block any new participants.

**Comment by PhynixP** [comment]
Thank you !
I will test it later and give you antwer

**Comment by PhynixP** [comment]
It work for me :)
Update:
1.The Server ist start with param.session.max_participants = 1
now i will test with a friend:)
2.The Server ist start with param.session.max_participants = 0
in the playersearch screen i have the error 2306-0111

**Comment by kinnay** [comment]
I see you figured it out already, but please don't use github issues as a helpdesk. It's okay if you ask questions that may be related to bugs in my code, but the IndentationError was obviously an issue in **your** code.

**Comment by PhynixP** [comment]
Just wanted to let you know that it is possible to play with 2 people.
So far everything works (statistics, bonus, etc.
