### ISSUE TITLE
Error 2623-1011 on round start after matchmaking

### ISSUE THREAD

**Issue by just-another-random-person** [kinnay/SMB35#3]
When connecting to my server, matchmaking works (players that join and leave show up properly, late joining players get the correct gamestart countdown time).

However, once countdown finishes, and game is about to start with "Here we go..." message, game doesn't start and instead clients get an "Error 2623-1011".

No visible errors are seen in the server logs (with either logging.INFO or logging.DEBUG levels).

**My setup**

- Brand new clean Ubuntu 20.04 VPS
  - nothing installed except python3 (Python 3.8.5 according to --version), pip-python3, git, and snap/certbot
  - Used git clone on https://github.com/kinnay/NintendoClients/
  - Ran "pip3 install ." in the cloned folder,  successfully with seemingly no errors
  - Used git clone on https://github.com/kinnay/SMB35
  - Created "resources" folder inside the cloned folder, and copy-pasted all the generated *.pem files into it, which were generated as so:

![image](https://user-images.githubusercontent.com/6364606/119647982-82be3a80-be53-11eb-918b-f03a4480130a.png)

- Then, I simply ran "python3 main.py"

Below are the consoles I used to connect:

- Console 1: 
  - version 12.0.0|AMS M.19.3|E in settings
  - brand new clean Atmosphere install, added nothing except
    - exosphere.ini for emummc prodinfo blanking
    - my own IPS in atmosphere/exefs_patches/patch
    - 90DNS set up in the emuMMC

- Console 2:
  - version 11.0.1|AMS M.19.3|E  
  - brand new clean Atmosphere install, added nothing except
    - exosphere.ini for emummc prodinfo blanking
    - my own IPS in atmosphere/exefs_patches/patch
    - 90DNS set up in the emuMMC

Also, Hekate's "Fix Arch Bit" is used afterwards every time files are copied over.

The IPS patch file I am using was created like so:

![image](https://user-images.githubusercontent.com/6364606/119649089-d1b89f80-be54-11eb-8346-5a8ed3fe53f9.png)

After they connected, during matchmaking, they show up properly on the dashboard:

![image](https://user-images.githubusercontent.com/6364606/119649236-fc0a5d00-be54-11eb-973f-e97b796fa6b5.png)

Below is the logging.INFO log, from startup all the way up to Error 2623-1011

![image](https://user-images.githubusercontent.com/6364606/119649770-98ccfa80-be55-11eb-93e7-e8a275b16f47.png)
![image](https://user-images.githubusercontent.com/6364606/119649775-9b2f5480-be55-11eb-8623-f52b23d1ba36.png)

Here is the logging.DEBUG log (note at the end I close the software on both Switches):
- https://pastebin.com/raw/DdcHVif5

--- 

More Testing:

- I replaced the patch file with the stock one that redirects to "smb35.ymar.dev:20000", and the game works properly after matchmaking. 
  - Nothing else was replaced/changed except the patch file.
- I replaced the patch file with one I created to connect to "bluephynix.de:20000", the person in the other issue. The game works properly after matchmaking.
- Replaced it back with my own patch file and I get "Error 2623-1011" when the game is about to switch from matchmaking to relay server mode.
  - Matchmaking works perfectly (leaving, rejoining, etc. shows up properly, as well as the reduced countdown timer), can also play Practice mode.

It must be something with my setup, but my setup is pretty barebones as it is
- nothing on the VPS but python3 and let's encrypt certificate from certbot (no webserver even)
- ports are confirmed open (matchmaking works, dashboard works)
- clean Atmosphere installs on Switches 
- replacing the patch file with other servers works (ymar and bluephynix patch files work)

I've tried it on other VPS boxes I had access to (even tried it on an OSX box with Python 3.7), as well as some other certs available to me, and I get the same error. But it instantly works once I point it to those two known working servers.
EDIT: Just tried to update my VPS to Python 3.9 and run it there, still got the same error code.

I hope you can help me figure this out.

**Comment by just-another-random-person** [comment]
Also, after closing the error code dialog, attempting to do anything doesn't work anymore.
I tried viewing the coin ranking screen with the empty/dummy values, or trying to queue up again for matchmaking, but it just forever gets stuck at the "Loading..." screen, and the server logs go crazy with the "unexpected packets"

![image](https://user-images.githubusercontent.com/6364606/119691749-69ca7f00-be7d-11eb-9cf8-4cf575384a50.png)

Hope you can help me figure out what's wrong.
I've been fiddling with this for over 48 hours now, I just reinstalled Ubuntu on my VPS and just did nothing except install/run certbot, install git and python3-pip, clone kinnay/NintendoClients and "pip install .", clone kinnay/SMB3, create a resources directory and copy over the pem's fullchain and privkey, and run python3 main.py

Still the same error :(

**Comment by just-another-random-person** [comment]
Nvm, I somehow missed this:

> Also change the domain name here: https://github.com/kinnay/SMB35/blob/master/source/main.py#L196

**Comment by kinnay** [comment]
Hi, sorry I didn't reply. I'm glad you figured it out.
