### ISSUE TITLE
Disconnected players stay in the game, become "immortal", and defeat all players

### ISSUE THREAD

**Issue by just-another-random-person** [kinnay/SMB35#6]
We noticed in several games, some people would be frozen in place, never time out, and beat us all after we reach fastest red timer and time out.

At first we thought it was a hacker, until one of us got a connection error and also had the same result.

Now we can reproduce it reliably:
**Steps to reproduce**:
1. Have 2 or more players join a lobby, then wait until the game starts
2. One player presses the home button, closes the game by pressing X.
3. That player is now "immortal" in the game, will never run out of time, and cannot be beaten by the remaining players.

This is the error that appears once they close the game:
![Screen Shot 2021-05-30 at 6 15 46 PM](https://user-images.githubusercontent.com/6364606/120113181-e5913800-c1ab-11eb-8693-e5c596100cf2.png)

And of course, this initiates the ClosedResourceError stacktrace spam until the end of the game
![Screen Shot 2021-05-30 at 6 17 52 PM](https://user-images.githubusercontent.com/6364606/120113679-212d0180-c1ae-11eb-9803-aa65f6e92173.png)

**Comment by kinnay** [comment]
Yeah, removing disconnected nodes will probably fix this. We will also have to send a [node notice packet](https://github.com/kinnay/NintendoClients/wiki/Eagle-Protocol#node-notice) to all other nodes to inform them that a node was removed.

I think we should also send a node notice packet when a new node joins the session, but that's probably unrelated to this issue.

**Comment by just-another-random-person** [comment]
So I've been trying my hand at this...  
After all, all I need is to make all other clients realize one disconnected, somehow, and they should mark it dead themselves... right?

So I did 3 types of attempts, first was to broadcast a Disconnect RPC packet, with the source node_id set to the disconnected client's.  
Maybe they'll interpret it as "the node with source node_id is disconnecting, we should mark the player dead".  

I thought I'll just do this for everyone who gets marked as disconnected, maybe they'll automatically get marked as dead.

![Screen Shot 2021-06-02 at 3 17 44 AM](https://user-images.githubusercontent.com/6364606/120381316-dac5d700-c354-11eb-9198-964f60f59646.png)

Just modified it a bit to allow empty payloads (as the disconnect packet has)

![Screen Shot 2021-06-02 at 3 17 57 AM](https://user-images.githubusercontent.com/6364606/120381419-f92bd280-c354-11eb-916e-8f2e7fdb5af3.png)

Catch the usual stacktrace culprit when someone disconnects

![Screen Shot 2021-06-02 at 3 18 10 AM](https://user-images.githubusercontent.com/6364606/120381458-0648c180-c355-11eb-8eaf-1f8c05ad4ec7.png)

And just copy relay_rpc logic to broadcast the packet

![Screen Shot 2021-06-02 at 3 19 54 AM](https://user-images.githubusercontent.com/6364606/120381476-0c3ea280-c355-11eb-84a8-bba15d278037.png)

.... and it ended up disconnecting everyone when someone exited out of the game. I guess the disconnect packet just makes the client disconnect, irregardless of the node id in the source field.

**Comment by just-another-random-person** [comment]
So I tried to instead just remove the node, and broadcast a node notice packet that it was removed, as originally recommended.

![Screen Shot 2021-06-02 at 3 22 08 AM](https://user-images.githubusercontent.com/6364606/120383547-95ef6f80-c357-11eb-892f-379142c65e8c.png)

![Screen Shot 2021-06-02 at 3 22 14 AM](https://user-images.githubusercontent.com/6364606/120383577-a0116e00-c357-11eb-8005-f44a7134a1c9.png)

Added a send_node_notice method to EagleClient

![Screen Shot 2021-06-02 at 3 22 35 AM](https://user-images.githubusercontent.com/6364606/120383835-f383bc00-c357-11eb-8575-0903eaefcc0b.png)

Catching the usual stacktrace culprit again when someone disconnects

![Screen Shot 2021-06-02 at 3 25 56 AM](https://user-images.githubusercontent.com/6364606/120383867-fd0d2400-c357-11eb-9380-efb3f6b59807.png)

And copying the relay_rpc logic again to broadcast the node notice

![Screen Shot 2021-06-02 at 3 26 37 AM](https://user-images.githubusercontent.com/6364606/120383925-0e563080-c358-11eb-9388-54ea70e530a7.png)

Now I'm sure the methods are being called, I filled the entire thing with logger.info calls everywhere.

But nothing happens. No idea what I'm doing wrong (probably a lot), but I'm trying to cut corners just to make it work, and I've never coded in Python before.

But yeah, everything gets called but nothing happens in game.

**Comment by just-another-random-person** [comment]
Final attempt was to just try to directly kill the player that disconnected by broadcasting a "Dead" Mario 35 RPC packet.

Added a few new properties to hold some necessary data:

![Screen Shot 2021-06-02 at 3 27 05 AM](https://user-images.githubusercontent.com/6364606/120384337-9d634880-c358-11eb-815a-a5fdfde3ce78.png)

![Screen Shot 2021-06-02 at 3 27 16 AM](https://user-images.githubusercontent.com/6364606/120384410-b2d87280-c358-11eb-834d-d008a5257c12.png)

![Screen Shot 2021-06-02 at 3 27 29 AM](https://user-images.githubusercontent.com/6364606/120384422-b7049000-c358-11eb-92e8-03eeea2893d0.png)

![Screen Shot 2021-06-02 at 3 27 36 AM](https://user-images.githubusercontent.com/6364606/120384435-bc61da80-c358-11eb-8aec-792e3caf6a3d.png)

Grab the data from the "AddPlayer" Mario 35 RPC Packet (as it seems to be the only packet that will have one each for all players)

![Screen Shot 2021-06-02 at 3 27 43 AM](https://user-images.githubusercontent.com/6364606/120384583-ee733c80-c358-11eb-922b-02ffcbbf1481.png)

![Screen Shot 2021-06-02 at 3 28 13 AM](https://user-images.githubusercontent.com/6364606/120384604-f337f080-c358-11eb-8018-8b804848dc83.png)

![Screen Shot 2021-06-02 at 3 27 52 AM](https://user-images.githubusercontent.com/6364606/120384631-fb902b80-c358-11eb-8e4a-1eb861fe7ea1.png)

Now I know the RPC packets are relayed, with the correct node IDs, by littering the code with logger.info's.  
I was even able to grab the player's names (the ascii ones anyway, I've tried a few encodings with Japanese symbols and others, and I can't seem to get it).

But still nothing happens when the "Dead" packet is broadcasted.

At first I was using zeroes for all the "unknown" values, but eventually, I modified some to look like the values the game actually sends when someone dies. Still nothing, either there's a checksum I'm failing or I'm misunderstanding something fundamental on how this all works.

(sorry it's all a mess, not as concise or elegant as your original code, but yeah, my first time with Python and rushing to get this to work)

**Comment by kinnay** [comment]
> Added a send_node_notice method to EagleClient

The source node should be set to 0 in the node notice packet. Instead, the node id of the disconnected client is part of the packet payload. It's 16 bits before the server time field. The game is probably ignoring your node notice packet because you forgot this field.

**Comment by just-another-random-person** [comment]
Totally overlooked that, thanks.

So I changed it to this:

![Screen Shot 2021-06-02 at 5 11 33 AM](https://user-images.githubusercontent.com/6364606/120391330-6fcecd00-c361-11eb-997a-b53d011af996.png)

And now I get error code 2623-0001 when the other player closes their game.

Pretty stumped, I'll try to tinker with the available options some more, but I think I've gone as far as I can go without any reverse engineering.

**Comment by just-another-random-person** [comment]
So I tried to do it properly:
- type 4 node notice to any new client
- type 0 node notice to any existing clients when a new client joins
- type 3 to other clients when one disconnects

change 1
![Screen Shot 2021-06-04 at 10 03 46 PM](https://user-images.githubusercontent.com/6364606/120890694-07b90900-c637-11eb-962e-233119aed8e1.png)
change 2
![Screen Shot 2021-06-04 at 10 04 29 PM](https://user-images.githubusercontent.com/6364606/120890696-0b4c9000-c637-11eb-8bf0-d29d1e0248fb.png)
change 3
![Screen Shot 2021-06-04 at 10 04 49 PM](https://user-images.githubusercontent.com/6364606/120890699-0ee01700-c637-11eb-9d05-c229a4ad5e7d.png)

Basically these are the new changes (aside from the other ones above already).

Still the same problem, error code 2623-0001 when the other player closes their game.
Not sure but is it possible the original server explicitly kills off the disconnected players by sending a "Dead" packet?
The last 5 bits seem to be some kind of checksum, otherwise the "Dead" packet gets ignored.

Also, the original server's behavior is different for disconnected clients:  
players that die normally [not KOd, but from normal enemies or pits] have half their coins go to the "prize pot"  
players that disconnect have ALL their coins go to the "prize pot"

This makes me realize, it may be possible the last few bits of the "Dead" packet refers to the player ID of who killed said player. I'll try to experiment with that angle instead a bit more.

**Comment by kinnay** [comment]
I pushed a fix. When I tested it the player that disconnected died immediately. Can you let me know if it works for you?

**Comment by just-another-random-person** [comment]
It works!

I can't believe the only missing thing was that the node notice (for all nodes [type=4], or node added [type=0])  
had to be sent AFTER client ready.

I even tried it in my code above, simply moved the 2 lines that relay node notice type 0 and 4 from EagleClient.process() to process_client_ready() and it also worked!

Of course, your code is much cleaner and more concise.
Thanks for the fix!
