### ISSUE TITLE
this alternative server method to do in other games?

### ISSUE THREAD

**Issue by FelipeBand657** [kinnay/SMB35#7]
I was wondering if this method you used to use an alternative server instead of the nintendo server is possible to be used in other games like: splatoon, smash, mario kart ...

**Comment by kinnay** [comment]
Yes! Almost every Switch game that has online features uses NEX servers, so the servers are all quite similar.

My SMB35 server only implements the services and methods that are required to play SMB35, but if you implement more services you can use it for other games too.

**Comment by FelipeBand657** [comment]
wow this is very good.
do you intend to implement this in other games?

**Comment by kinnay** [comment]
No, not currently. Other games are still playable on Nintendo's servers, so there is not much incentive.

**Comment by FelipeBand657** [comment]
I understand more if one day I want to do for other games know that I and several people are waiting for this due to the limitation of the lan play ...
thanks
