### ISSUE TITLE
Licensed as GPLv3, should be AGPLv3

### ISSUE THREAD

**Issue by Nolij** [kinnay/SMB35#9]
In a scenario such as this where its server software under GPLv3 hosting a server does not qualify as "distributing" and therefore does not actually require source code to be made public.

It should instead be licensed under AGPLv3, which contains an affero clause, which also makes distribution of services over a network such as the internet qualify as "distributing".

In its current state it may as well be public domain with no protections on it due to its nature.

**Comment by kinnay** [comment]
Thanks, sounds reasonable. I'll change it.

**Comment by Nolij** [comment]
> Thanks, sounds reasonable. I'll change it.

I submitted a pull request. Merging that should fix it.

**Comment by kinnay** [comment]
I'm having second thoughts about this. On the one hand, it would be cool if everyone publishes their source code. On the other hand, I'm not sure if I want to hinder people from using my code, even if they want to keep their changes private for whatever reason.

I'm still leaning towards AGPL. Just wanted to share my thoughts.

**Comment by Nolij** [comment]
> I'm having second thoughts about this. On the one hand, it would be cool if everyone publishes their source code. On the other hand, I'm not sure if I want to hinder people from using my code, even if they want to keep their changes private for whatever reason.
> 
> I'm still leaning towards AGPL. Just wanted to share my thoughts.

May as well make it not GPL at all in that case if you don't want an open-source requirement, However I'm fairly certain once you make a project GPL it can only be released under GPL unless completely rewritten, so it's too late for that (unless I'm wrong).

Considering the information sent to the server I'd feel safer playing on 3rd party servers if their source code is public. I haven't looked too much in to the inner workings, but I wouldn't be surprised if the software could be modified to get connected clients banned.

**Comment by kinnay** [comment]
> I'd feel safer playing on 3rd party servers if their source code is public.

Yeah that's true. I'm keeping AGPL.

> I'm fairly certain once you make a project GPL it can only be released under GPL unless completely rewritten, so it's too late for that

I think that only applies to other people that want to use my code. Because I'm the owner of the code, and no one else has made significant contributions, I can change the license at any time. However, that doesn't revoke the old license, so if people don't like the new license they can still use an old version of the code that had the old license. They just wouldn't be able to use any changes that I make to the code under the new license.
